"""add provider_message_id to notifications_sent

Revision ID: 02180c11c28d
Revises: 4e7a13e35276
Create Date: 2026-08-17 18:14:19.215580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '02180c11c28d'
down_revision: Union[str, None] = '4e7a13e35276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications_sent', sa.Column('provider_message_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_notifications_sent_provider_message_id'), 'notifications_sent', ['provider_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_sent_provider_message_id'), table_name='notifications_sent')
    op.drop_column('notifications_sent', 'provider_message_id')
    # ### end Alembic commands ###
