"""add quota_units to api_call_logs

Revision ID: 4e7a13e35276
Revises: 1cbd114abc00
Create Date: 2026-08-17 17:53:00.926819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4e7a13e35276'
down_revision: Union[str, None] = '1cbd114abc00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_call_logs', sa.Column('quota_units', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_call_logs', 'quota_units')
    # ### end Alembic commands ###
